set(_AMENT_PACKAGE_NAME "turtlebot_control")
set(turtlebot_control_VERSION "0.0.0")
set(turtlebot_control_MAINTAINER "megsindelar <megansindelar2023@u.northwestern.edu>")
set(turtlebot_control_BUILD_DEPENDS "rclcpp" "std_msgs" "sensor_msgs" "OpenCV" "cv_bridge" "image_transport" "ament_index_cpp")
set(turtlebot_control_BUILDTOOL_DEPENDS "ament_cmake")
set(turtlebot_control_BUILD_EXPORT_DEPENDS "rclcpp" "std_msgs" "sensor_msgs" "OpenCV" "cv_bridge" "image_transport" "ament_index_cpp")
set(turtlebot_control_BUILDTOOL_EXPORT_DEPENDS )
set(turtlebot_control_EXEC_DEPENDS "rclcpp" "std_msgs" "sensor_msgs" "OpenCV" "cv_bridge" "image_transport" "ament_index_cpp")
set(turtlebot_control_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(turtlebot_control_GROUP_DEPENDS )
set(turtlebot_control_MEMBER_OF_GROUPS )
set(turtlebot_control_DEPRECATED "")
set(turtlebot_control_EXPORT_TAGS)
list(APPEND turtlebot_control_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
